### ISSUE TITLE
Optionally terminate expensive spot instances when another spot instance type is better priced

### ISSUE THREAD

**Issue by cristim** [cristim/autospotting#102]

**Comment by xlr-8** [comment]
I'm wondering how efficient that would be?

If the prices are stable, it should be fine; but as we would start comparing spot prices against another, if some instances "are flapping" in terms of price, we might kill performances, no?

e.g.: 2 spot instances that are compatible and around the same price (let say A: $0.10/h and B: $0.12/h) depending of the price evolution of each (A becomes $0.11/h B becomes $0.10/h and vis-versa through time), we would re-create a new one, and then later delete it because the other one would have had a price drop.

WDYT?

**Comment by cristim** [comment]
That's a good point,I think this should be triggered only by significant price difference (say 50%) seen over long periods of time, maybe over a day or two. 

Frequent churn would be worse because of the duplication we have during the replacement procedure

**Comment by xlr-8** [comment]
I think it should indeed contain some sort of percentage for such price change, if you don't mind, I'd still like to be able to know how frequently that happens, to know if such feature would really make sense or not; but that might be a bit tricky to do :)

**Comment by cristim** [comment]
With the recent smooth spot prices I doubt this happens so often anymore.
I'll close this for now and if I see it in the wild we can reopen it.
