### ISSUE TITLE
Autoscale Down temporarily causes less than minimum on-demand number and may cause downtime on small groups

### ISSUE THREAD

**Issue by ahaverbuch** [cristim/autospotting#104]
# Github issue #

## Issue type ##

Feature Idea

## Summary ##

We are seeing an issue on autoscaling groups that are  autoscaling while autospotting is running.

Two fixes would help - this covers one of them (#103 is the other)
1) If you have an environment, say like this: 8 machines, min of 4 on-demand, oldest-instance for scale down policy. Autospotting runs, you get 4 on-demand (older), 4-spot (which are newer, as they replace other on-demand). If you then scale down, say to 6, you end up with only 2 on-demand, and 4-spot, which is smaller than the number you intend. It would be nice to have support to bring back to on-demand to get back to the intended level in order to minimize risk of spot market volatility killing a larger % of machines than intended to be running.

**Comment by cristim** [comment]
I guess we could terminate a spot instance if the ratio of spot vs on-demand is more than configured, and let autoscaling bring up a new on demand instance in its place

**Comment by xlr-8** [comment]
Correct me if I'm wrong, but if you specify `-min_on_demand_number=4`, shouldn't this behave as you expect? Or are you making a point about ratio between on-demand/spot instance as @cristim suggested?

That's what this function is intended for: https://github.com/cristim/autospotting/blob/master/core/autoscaling.go#L145, if you end-up in a situation with more spot instances, than on-demand required, then a spot instance gets terminated in order to bring back progressively this requirement.

**Comment by ahaverbuch** [comment]
That's good to know. That function does cause the behavior of getting back to on demand ratio eventually. But it actually itself can cause an issue as it's not graceful; if you are running close to the minimum number of machines you need to handle traffic, the terminate random spot will bring you under at least until the on demand machine comes up

If instead it did the opposite of the spot bring up, by bringing up an on-demand outside of the asg, then attaching it after grace period, then detaching spot, you wouldn't fall under the number of machines intending to be running.

**Comment by cristim** [comment]
Yes, it's not graceful, but remember that you had just scaled down, which means you are likely to have more than enough capacity in the group so losing one more spot instance(which may anyway happen at any time due to market price fluctuations) and waiting for AutoScaling to replace it with a new on-demand node shouldn't cause much problems.

Have you seen this causing problems in your environment?

**Comment by ahaverbuch** [comment]
I agree this can happen at any time due to spot, but there's scenarios where this forces an error state where it doesn't need to.

I see two items:

1) the spot terminator isn't checking for grace on the new on-demand if I am reading correctly. So if it's more than 5 minutes, let's say, then one can end up force terminating multiple spot nodes before on-demand come up healthy. Doing a detach/attach would smooth that out.

2) small ASGs. A test one ran into that. It normally runs with one machine, but can scale up. I turned on autospotting as a test, so had 1 on-demand, 1 spot. Scale down then terminated the on-demand as it was older, leaving 1 spot left. The code above would then terminate that 1 spot, leaving no nodes at all until the new one comes up.

I know having a single machine minimum isn't an HA solution in any way, but any multiplier of 1 is still suspect to similar fallout on scale down depending on timing, which is exasperated, either because of market rate increases or this code, by having only spot machines left after scale down.

**Comment by ahaverbuch** [comment]
For that second scenario, that's if the config is min on demand of 1., min on the ASG of 1 as well.

**Comment by cristim** [comment]
The current implementation clearly has limitations in graciously handling these scenarios.

I would like a fix for this particular reverse replacement limitation to be done in a generic way that would allow us to use it for multiple use cases, maybe by building something that would be able to replace any instance with whatever is appropriate for it at that moment:

- on-demand with spot - the normal replacement case
- spot with on-demand - the reverse replacement, for recovering after loss of on-demand capacity or scaling in of on-demand in a group which has to maintain certain on-demand capacity like in the scenarios mentioned above
- spot with spot - in case we find a significantly better priced spot instance, like stated in #102

All these need to be downtime-free by draining traffic from the instance being replaced, and able to properly handle the disappearance of the instance being replaced, or other such edge cases.

**Comment by xlr-8** [comment]
The problem of draining instances is well-known and @cristim already started working on that.

> For that second scenario, that's if the config is min on demand of 1., min on the ASG of 1 as well.

To be more precise, for the second scenario to be problematic, that would imply:
* Autospotting minimum on-demand config set to 1
* minimum ASG size set to 1
* and desired ASG capacity size set to 1 as well - otherwise it wouldn't happen

Despite being quite an awkward if not uncommon configuration for an ASG. I see at least 2 "easy ways" to solve that problem.
* One could be to ensure that some on-demand are running at least, increasing temporarily the desiredCapactiy size in order to have at least 1 on-demand and then reverting back to 1 could do.
* Set the auto-scaling policy to remove the newestInstance, in order to avoid deleting on-demand instances and encourage spot-instances to be the one replaced.

I'm trying to think of use-cases where both solutions this could be problematic.

**Comment by cristim** [comment]
There was a discussion happening on #117 but actually referring to this issue:

I've been also thinking and commented there that we could increase the group capacity to compensate for lost on-demand capacity beyond the desired minimum, and once the on-demand instance is out of its grace period it could detach and terminate the corresponding spot instances in an AZ where we have the maximum number of instances, in order not to cause a rebalancing between AZs, but this is not really guaranteed, because te additional capacity may interfere with the scaling policies, the instance may be launched where we don't want it because of balancing concerns. Ideally we want to launch in an AZ where we also have some spot nodes which could be terminated without rebalancing the group, and if we leave this to AutoScaling it will not be likely to happen.

So I think it would be safer and easier to simply launch on-demand nodes outside the group just like we do with spot nodes, and reverse the replacement/termination logic, in order not to interfere with the scaling policies and to avoid any rebalancing after the termination.

**Comment by universam1** [comment]
I wanted to stress this problem which is actually happening to me to ending up with `0` instances which is not acceptable!
When the ASG scales-in to 1 instance on idle times, this will destroy the oldest instance which is usually an on-demand one. This is not a problem until autospotting realizes that there is `minimum on-demand ==1` and destroys the remaining spot instance! 😭 
```
AutoScalingGroup-VKIKxxxxx3BH8M Found 0 on-demand instances running on a total of 1
autoscaling.go:155: Currently less OnDemand instances than required !
autoscaling.go:159: Terminating a random spot instance i-0e7a4e3fcb11a3452
```

I would consider @cristim this a actually a dangerous bug, because it renders AS not usable for ASG <2 . 
Maybe as a intermittent solution one could catch this situation and at least not destroy the last unicorn. Of course, an active replacement with on-demand would be the right solution.

**Comment by cristim** [comment]
@universam1 I don't have enough bandwidth for taking care of this, if you need this functionality please consider contributing it.

In the meantime you can set the group minimum capacity to two, as stated in the documentation, running groups of a single instance on spot setups is a bad idea.

**Comment by universam1** [comment]
Do you agree that a termination if ASG size is 1 is always false?
Then I can contribute a guard for this case.

**Comment by cristim** [comment]
@universam1 that should be fine, I'd approve a contribution which avoids taking any actions on groups having Min=Desired=1.

But this won't protect you against the case in which that single spot instance left in the group after scaling in will get outbid by market conditions.

Using groups of minimum size 1 is asking for trouble.

**Comment by universam1** [comment]
Fully agree with you, a ASG of 1 with spot instance is a dangerous situation. At least this software is then not to blame for the service going down.

**Comment by cristim** [comment]
I think #164 largely mitigates this issue which I would like to get closed. 

Please reopen or create a new one in case of other edge cases that need to be handled.
