### ISSUE TITLE
Implement retry logic for tagging of spot instance requests

### ISSUE THREAD

**Issue by cristim** [cristim/autospotting#111]
This hopefully fixes #20

**Comment by xlr-8** [comment]
As AWS announced in the past couple months, tag can now directly be transmitted to the instances, so that we don't need to call CreateTags - if we know the tag in advance, which I think is our case - but can simply pass them to the request.
I feel like it might be an easy fix for the apparent problem that we have, as we wouldn't have to take care of that, AWS would.

See the type: https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#SpotInstanceRequest

On the other hand the aws.Config that we provided is fairly simple:
https://github.com/cristim/autospotting/blob/master/core/connections.go#L22-L25

We do not set any MaxRetries, which means - according to the doc - that the services defaultMaxRetries is being used, but I couldn't get that value for sure.
I found: https://github.com/aws/aws-sdk-go/blob/master/aws/client/default_retryer.go#L23-L25 - which sounds a bit much to me; while on .net SDK it is between 4 & 10 depending on the service: http://docs.aws.amazon.com/sdk-for-net/v2/developer-guide/retries-timeouts.html

So it might be worth checking that value, and eventually increasing it if need be - as if AWS is failing even though it has a retry implemented, we might be looking at the wrong place.

**Comment by cristim** [comment]
@xlr-8 this is not about the tags set on the instance (which could surely be optimized as well), but about the tags set on the spot instance request (SIR) object which identifies for which group it was created so we can attach its spot instance to the correct group.

This tagging is only attempted once, and sometimes we get a 400 because the SIR object is not yet ready to accept requests. From outside this looks like a race condition with propagation on some eventually-consistent storage.

 I think normally the SDK's retries happen only in case of API throttling, not in case of real response errors, like it happens in this case.

I started working on this and I have some code locally, but I'm struggling to properly write the tests for it since it's using time.Sleep, and I don't want the tests to sleep.

Do you have any suggestions on how to mock this?

**Comment by xlr-8** [comment]
@cristim Yes, I'm aware this isn't on the instance, but the link I provided was for the SIR type, which includes tags. This is why I thought we could update the code to include the tags into the SIR rather than waiting for which-ever condition to allow us to do so.

Am I missing something out?

**Comment by cristim** [comment]
Setting the SIR tags on creation would still be an improvement, apparently this should be supported by the API.

Unfortunately the instance tagging from SIR creation seems to be still unsupported, hopefully it will be available later on.

**Comment by roeyazroel** [comment]
@cristim @xlr-8  Maybe the best solution for this issue is a greedy workaround - if error (error 404 when trying to get the SIR) retry after X seconds.

**Comment by cristim** [comment]
@roeyazroel that was also my first attempt, but apparently the API now also allows setting the tags on creation, which would be simpler and preferable, if it actually works.

**Comment by cristim** [comment]
I closed #113 for now, will soon send a PR implementing the logic as described by @roeyazroel

**Comment by cristim** [comment]
Closing the issue, this was solved in #116
