### ISSUE TITLE
Spot instance is orphaned if AS is deleted a few minutes after creation

### ISSUE THREAD

**Issue by esdu** [cristim/autospotting#128]
# Github issue #

Spot instance is orphaned if AS is deleted a few minutes after creation because _the instance is not tagged_ yet.

## Issue type ##

- Bug Report

## Steps to reproduce ##

- Create an Autoscaling Group
- Wait 2 minutes so it starts spinning up a spot instance
- Delete the Autoscaling Group before the spot instance is tagged (this seem to take a few minutes at least)

## Expected results ##

When AS is deleted, all its spot instances should be deleted.

**Comment by cristim** [comment]
The spot instances are tagged immediately after launching, the real reason why this is happening is because they are not yet added to the group, and the group only terminates its own instances.

These orphans should be terminated by autospotting when trying to get them attached to the group in case the group is gone, but the current logic doesn't consider this case yet.

This is not really a bug, it's just missing the orphans cleanup functionality.
Please try to create a PR implementing this kind of clean-up logic.

Have a look at autoscaling.go, you can find there the spot  instance attachment logic which needs to also handle this case

**Comment by cristim** [comment]
After a bit of thinking I think this is only doable in region.go, where we would need to add an orphan instance cleanup logic after processing all the existing autoscaling groups.

Autoscaling.go will only look at the current autoscaling groups, so if you deleted the group there is no way to have a handling logic for the orphaned instances created for the deleted group

**Comment by cristim** [comment]
@esdu it would be awesome if you could submit a PR implementing this clean-up logic. It's a quite small fix that should be quite beginner friendly.

Do you think you have time to do this anytime soon?

**Comment by esdu** [comment]
@cristim Cool yes I'm interested, I have a little too much going on these days but I should be able to get to this in mid-September, if you don't mind waiting!

**Comment by cristim** [comment]
Thanks, I see little urgency in this issue, and it would be a great way for you to get started into the project.

**Comment by cristim** [comment]
This is expected behavior, instances in the process of replacement can't be cleaned up when deleting the stack, it's up to the user to make sure that the stack is deleted when there are no unattached instances
