### ISSUE TITLE
Security group not found in VPC

### ISSUE THREAD

**Issue by vinczente** [cristim/autospotting#143]
## Issue type ##

- Bug Report ?
- Documentation Report ?

## Build number #

```
439
```

## Configuration ##

default configuration

## Environment ##
```
region: eu-west-1
env : DefaultVPC (not sure)
conf: default
```

## Summary ##

Hi there,

I decided to give autospotting another go (ah !), I did make it work in the past but right now, in  a new setup, I am having an issue with something I have little understanding.

Here is what I can see in the log of the lambda function:

```
Failed to create spot instance request for {AutoScalingGroup} InvalidGroup.NotFound: The security group {SecrurityGroup} does not exist in VPC {VpcId}
```

Can you help me understand what I misconfigured ?

Thank you !

## Steps to reproduce ##

This is a basic setup for AWS beanstalk, all created by AWS automation

## Expected results ##

instances to be replaced by spot instances

## Actual results ##

None of the instances are replaced by spot instances

**Comment by vinczente** [comment]
I think this is related

https://github.com/cristim/autospotting/issues/48

but I don't think any solution was found ?

**Comment by cristim** [comment]
The configuration cloning logic which makes sure your spot instances are identical to the on-demand instances currently assumes all VPC security groups are given by VPC ID and EC2 Classic VPCs are given by name.

The problem is in DefaultVPC the groups can still be configured by name when reusing infrastructure code initially written for EC2 Classic.

A proper solution working in all cases would be to attempt to describe the VPC both by name and ID, and use the whichever worked.

This is not yet done, someone would need to implement this functionality in the configuration cloning logic.

@vinczente If you want to give it a try I can help you get started.

**Comment by cristim** [comment]
@vinczente, as a workaround try to launch the application in an ordinary VPC

**Comment by cristim** [comment]
Closing as duplicate of #48
