### ISSUE TITLE
Cancel open bid for a long time and create new request for a different instance type. 

### ISSUE THREAD

**Issue by vivekdubey** [cristim/autospotting#166]
# Github issue #

## Issue type ##

- Feature Idea

## Summary ##

If a spot bid in a autoscaling group isn't fulfilled because of `capacity not available issue` for a very long time, autospotting doesn't try bid for other available instances with a similar price range, may be a little more.     

## Description ##
I have an autoscaling group running around 12 c4.xlarge instance. Autospotting managed replace three of on demand instances with spot instances with similar capacity. But  after replacing three, it created another request for instance type `r4.xlarge` but request was open for a few hours. 

Since, autospotting waits for the open request to be fulfilled before moving ahead and trying to replace instances in an autoscaling group the autoscaling group with on-demand keeps running for the time until the open request is fulfilled. 

## Feature Details ##

Autospotting could have a feature to cancel the request open for n amount of minutes and try to bid for a new instance of a different type. It could be a little expensive than the previous spot request (the cancelled one) but still it save more than by keeping the autoscaling stuck with a lot of on-demand instances.

**Comment by cristim** [comment]
Thanks, this would be a great improvement.

I am curious about the reason why this spot instance request is not fulfilled in the first place.

I guess the price for that instance type should be increased when out of capacity so that we can get a new one for another type. But if the price is still the lowest but it is actually unavailable then we are pretty much stuck with it.

What we could do is to time it out after a while as you proposed, but at the same time make sure to use a different type for the next spot instance request, launched immediately after the existing one is canceled

**Comment by cristim** [comment]
@gaurav-narra volunteered to work on this.

**Comment by CpuID** [comment]
I think this is possibly a symptom of the new [spot model](https://aws.amazon.com/about-aws/whats-new/2017/11/amazon-ec2-spot-introduces-new-pricing-model-and-the-ability-to-launch-new-spot-instances-via-runinstances-api/) introduced around re:Invent. See [this rundown](http://autoscalr.com/2018/01/04/new-aws-spot-pricing-model-good-bad-ugly/) on the changes and what to expect.

Just noticed the same issue, with spot requests being attempted but being left open with no capacity, see the screenshot below:

https://www.dropbox.com/s/lm3gxhdvga5e2zq/Screenshot%202018-03-13%2019.12.48.png?dl=0

Instead of having a high price, and being knocked out of the race during the autospotting evaluation, it gets chosen based on having a low stable price but then won't get fulfilled due to capacity. In my opinion this is a pretty backwards step of the way spot instances work, as it makes the supply/price equation far less transparent, but obviously AWS made the decision (for whatever reasons).

I think autospotting should somehow identify these situations and attempt the "next best candidate" instance type ideally (ordered by the standard criteria used to select the first option), after some kind of sane timeout (5-10~mins for an open spot request?).

**Comment by cristim** [comment]
@tootedom is working on a change to short-lived SIRs going forward.

To work around this issue we can keep them for more than 5min, so we have them until the next run, but then if we find them unfulfilled in the second run we can tag the group to blacklist them for their instance type for the next few hours, so then we skip that instance type for a while when creating new SIRs.

**Comment by CpuID** [comment]
> To work around this issue we can also tag the group to blacklist the unfulfilled instance type for the next few hours, so then we skip that instance type for a while as if it would be blacklisted in the group configuration. This could be done in an additional tag set on the group which we maintain ourselves based on this behavior.

+1, that solves the state storage question mark I had :+1: 

> @tootedom is working on a change to short-lived SIRs going forward.
> 
> The plan so far is to have the SIRs expire in less than 5min so we never time out the Lambda function runs.

@tootedom looking forward to it :)

**Comment by cristim** [comment]
Since #257 was merged this is no longer an issue, the SIRs are handled internally by AWS and should be cancelled if the instances fail to launch immediately, so AutoSpotting will keep running the on-demand nodes until it's able to launch a spot instance. 

The fall-back to other instance types is planned to be implemented in #263
