### ISSUE TITLE
Improve tagging system

### ISSUE THREAD

**Issue by xlr-8** [cristim/autospotting#171]
## Issue type ##

- Feature Idea

## Summary ##

Find better way to handle taging system - asynchronous for example.

## Details ##

The [pricing system for AWS Lambda](https://aws.amazon.com/lambda/pricing/) is based on the time spent at runtime by 100ms. And when we look at [the tagging code](https://github.com/cristim/autospotting/blob/687c852039cc2fea0b88b6b7d931626367a73094/core/spot_instance_request.go#L111) we can directly see that we can spend up to 1 minute waiting/trying to tag an instance.

1 minute means 600 cycles of 100ms, so if we could find a better way to do so (saving an artifact, making it asynchronous by plugging it to CloudTrail events, etc), that could save quite some time of execution.

I'm not sure how possible that is to do so for now, but that seems like an obvious way to improve time performance of the project.

**Comment by cristim** [comment]
Thanks for the proposal!

The main idea behind the instance tagging waiting loop is that sometimes instances use the tags for startup configuration so they need to be tagged from the very beginning so we can't afford to wait for the next run.

The current logic is a temporary workaround until we have tagging support when launching the spot request(last time I tried the APIs didn't support this).

Another implementation of the workaround would be to have a way to capture the instance launching event and apply the tags when the instance is launched, but it would increase the complexity of the architecture.

The sleep loop is much simpler and since Lambda offers a generous free tier that should cover this waiting time, which is anyway spent only when we launch new spot instances.

**Comment by cristim** [comment]
At re:invent AWS updated the RunInstances API call to allow launching spot instances without the need to use spot instance requests directly, and since this API call supports tagging, the instance will get the tags out of the box and we don't need to apply them after the fact.

This has the potential to simplify the logic significantly.

**Comment by xlr-8** [comment]
As mentioned, I have taken a look at the impacted code - despite the new calls being simple/straight forward - many portions of code will be impacted by this

**Comment by cristim** [comment]
I'm working on a large refactoring that replaces the current spot instance request mechanism with the RunInstances call, stay tuned

**Comment by xlr-8** [comment]
I will! Thanks for taking the time!

**Comment by cristim** [comment]
The RunInstances call implemented #257 is also addressing this issue.

The call is synchronous, so it's waiting for the new spot instances to be launched, but anyway the Lambda cost is so low that it doesn't make much difference.
