### ISSUE TITLE
Spot request expires after 7 days (ValidUntil default value)

### ISSUE THREAD

**Issue by phils** [cristim/autospotting#231]
## Issue type ##

- Bug Report

## Build number #

Current master code

## Summary ##

I've noticed that my spot request is marked cancelled, as it ran for more than a week.  The 'valid until' field is 7 days after the initial creation.

My instance wasn't terminated, ~~I believe it just went back up to the ondemand price.~~ Actually I just checked properly via cost explorer and it still charges me the spot price, so is there actually any bad outcome from having the spot request cancelled?

Looking at the API reference, it says 'ValidUntil' defaults to 7 days, which explains it.

Code does not specify ValidUntil in autospotting.go:

resp, err := svc.RequestSpotInstances(&ec2.RequestSpotInstancesInput{
		SpotPrice:           aws.String(strconv.FormatFloat(price, 'f', -1, 64)),
		LaunchSpecification: ls,
	})

Suggest autospotting should choose a date very far in the future?

**Comment by cristim** [comment]
Thanks for reporting this. This was previously discussed in detail under #222.

The plan going forward is to expire the SIRs after ~4 minutes, they are pretty much redundant after the instance started, and the fact that we have them there and need to keep track by describing them repeatedly causes problems on large installations due to API throttling.
