### ISSUE TITLE
Unable to import module 'handler': No module named handler

### ISSUE THREAD

**Issue by prashantdj1** [cristim/autospotting#233]
getting issue like below while running code:

START RequestId: 297b506e-25d1-11e8-9c6e-c5969e20a2e6 Version: $LATEST
14:12:52.163 autospot /aws/lambda/autospotting Unable to import module 'handler': No module named handler
14:12:52.163 autospot /aws/lambda/autospotting message='' •••

Can anyone please help

**Comment by cristim** [comment]
This is caused by updating the code installed before the change of the Lambda function to the native Go runtime, which unfortunately requires a few parameter changes on your CloudFormation stack. Previously we used the Python runtime with a wrapper library that loaded the Go code, which had a different entry point handler.

To fix you can update the stack parameters as you can see in the cloudfromation directory. You can also reinstall the stack from scratch, which will take the correct parameters out of the box.

**Comment by prashantdj1** [comment]
I am using terraform do that... Can you let me know what to do for that?

**Comment by cristim** [comment]
I saw you sorted it out in #234
