### ISSUE TITLE
license questions

### ISSUE THREAD

**Issue by kapilt** [cristim/autospotting#235]
autospotting looks really cool, but what's going on with the license here?  The src license looks like a two clause bsd variant but the binary license appears to be something a bit different, aka non free.

```
Permission is hereby granted, free of charge, to any person (the "User")
obtaining a copy of the official AutoSpotting binaries and associated
documentation files (the "Software"), to use it for up to 14 days for evaluation
purposes. Further use of the Software requires paying a licensing fee.
```

but then the docs also reference recommending using the binaries "It's usually recommended to use the provided binaries"

**Comment by cristim** [comment]
The source code is MIT licensed.

The easy to install precompiled binaries are proprietary and can be used for up to two weeks for free for evaluation, then you' have to contribute a small percentage of your savings via Patreon if you want to continue using them.

This is because offering them incurs some cost that has to be covered somehow, I simply can't afford to host and support them free of charge for everyone out there. Also, all the Patreon donations will encourage further development, the time I allocate on a monthly basis supporting people is more or less proportional to that Patreon income. You basically pay for the convenience and time you save by using them instead of compiling it yourself and also for some support if you run into issues.

You can always run it built from source for free but I won't support such builds so you're on your own if you do it.

**Comment by kapilt** [comment]
thanks for the clarification, and thanks for making autospotting opensource, obviously how you want to support/solicit is really up to you, i'd suggest wording and putting patreon link on the readme for those not using the official binaries to chip in as well to support opensource.
