### ISSUE TITLE
Please tag releases with tags / use github releases for terraform

### ISSUE THREAD

**Issue by thomaschaaf** [cristim/autospotting#255]
For us it would be great if we could reference a specific point in time. Git Tags would allow us to reference a specific version in terraform.

**Comment by cristim** [comment]
I'd do this if it can be automated so that I don't need to spend extra time manually creating the git tags and/or github releases. If you can contribute such automation I'd gladly accept it.

We currently have versioned binaries generated after every commit, have a look at our official builds [S3 bucket](https://cloudprowess.s3.amazonaws.com/index.html). You can take the git SHA from there and plug it into your terraform code when loading the autospotting module.

**Comment by cristim** [comment]
We now have a versioned module in the Terraform registry, see https://registry.terraform.io/modules/neillturner/autospotting/aws/0.0.8
