### ISSUE TITLE
Does not find all on-demand instances

### ISSUE THREAD

**Issue by goloroden** [cristim/autospotting#277]
## Issue type ##

- Bug Report

## Build number #

```text
nightly-882
```

## Configuration ##

- Kubernetes cluster setup using Kops
- 3 master nodes, 6 worker nodes
- Settings for `autospotting` are all default, except the instance type to use, which has been set to `m4.large`

## Environment ##

- AWS region:
  - autospotting: us-east-1
  - ASG to manage: eu-central-1
- Type of environment: VPC
- Anonymized launch configuration:

```text
(Where do I find this?)
```

## Summary ##

I have added the `spot-enabled` flag to an AGS and set it to `true`. For 5 of 6 instances things worked perfectly, but the 6th instance won't be replaced by autospotting. According to the logs, it says that no more on-demand instances were found – which is wrong.

## Steps to reproduce ##

n/a

## Expected results ##

All the 6 nodes should be replaced by spot instances.

## Actual results ##

Only 5 instance have been replaced.

**Comment by cristim** [comment]
Thanks for reporting this.

So far from what you described it seems like you are just running into capacity limits with the m4.large and you restricted it to a single instance type so it can't find any alternatives for now in that availability zone. If you give it enough time it should eventually launche one, but there is no guarantee on how long it takes.

Try to remove the allowed instance types and just set a disallowed list of instance types that are not compatible with your configuration, to allow the algorithm to maybe get you other similar instance types that may be able to launch. 

But that is just a guess, in order to be able to help please paste the anonymized logs of the failing run.

**Comment by goloroden** [comment]
As it seems, you're actually right.

Maybe the error message could be slightly better then 😉 
(It's a little bit misdirecting, if it tells you that no machines to update were found.)

Apart from that: Very nice project 👍

**Comment by cristim** [comment]
Thank you for the nice words, I really appreciate it.

To be honest I haven't seen this situation myself yet, it was just reported by various users. Please paste the misleading log entry and I will try to improve it.
