### ISSUE TITLE
Remove requirement to run in us-east-1

### ISSUE THREAD

**Issue by phils** [cristim/autospotting#94]
## Issue type ##

- Feature Idea

## Summary ##

The docs say:

> For technical reasons the stack needs to be launched in the US-East-1(Virginia) region, so make sure it's not created in another region.

Would be good to be able to run this in other regions where requirements dictate this.  Can you elaborate on the technical reason it must run in us-east-1 at the moment?  Thanks.

**Comment by cristim** [comment]
It's a CloudFormation limitation: when creating Lambda functions with CloudFormation it requires that the S3 bucket used for the function source code is located in the same region as the stack:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html

The bucket where TravisCI deploys the code after each build is located in US-East-1, so that's why the stack is must be created there as well.

If you want to use CloudFormation in a different region you will need to self-host your binaries, which means you need to take care of building the code and pushing it to your own S3 bucket, which has to be in that region.

As far as I know, the Terraform deployment code doesn't have this requirement, but I didn't try that yet.

**Comment by xlr-8** [comment]
I confirm the limitation isn't present in terraform, because no S3 bucket is being used.
The zip archive is being sent directly rather than stored on S3 like it is the case for Cloudformation.

It uses the `filename` parameter [1]: https://www.terraform.io/docs/providers/aws/r/lambda_function.html#filename. So as documented, an S3 bucket could be used, but as it could have been avoided I wanted to keep things simple & stupid.
Therefor the region being used would be the one specified in the CLI: https://github.com/cristim/autospotting/blob/master/START.md#install-via-terraform

[1]. https://github.com/cristim/autospotting/blob/master/terraform/autospotting/lambda.tf#L3

**Comment by cristim** [comment]
I think we can close this, since this is not a limitation of AutoSpotting but of the CloudFormation deployment mechanism when used against the provided TravisCI builds. When running a self-built or self-hosted S3 bucket (you should be able to `s3 sync` my bucket into yours), as well as when deploying with Terraform, the users don't have this limitation.

This is a stupid limitation of CloudFormation which I have no plans to mitigate, I won't provision the official builds S3 bucket in every single AWS region.

@phils If this is important to you please raise this to AWS, once they fix it in CloudFormation it should work out of the box.

**Comment by phils** [comment]
A big part me opening this issue was simply to understand the limitation (the existing documentation didn't elaborate).  You gave some good explanations in this ticket which I think would be perfect to add to the documentation pages (to help the next person who comes along).  Thanks.

**Comment by cristim** [comment]
Please send a PR with the  doc change, I will gladly accept it.
